---
apiVersion: v1
kind: Secret
metadata:
  name: admin-user-password
type: Opaque
stringData:
  password: DB_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: cloud
type: Opaque
stringData:
  ADMIN_PASSWORD: "SOME PASSWORD"
  NX_CLOUD_MONGO_SERVER_ENDPOINT: "MONGO ENDPOINT"